version: '3'
services:
#  Proxy
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-proxy/sites-enabled:/etc/nginx/conf.d/sites-enabled"
    restart: "always"

#  Main app
  nginx-main:
    container_name: nginx-main
    image: nginx:latest
    depends_on:
      - nginx-proxy
    volumes:
      - "./main/nginx/serveur.local.conf:/etc/nginx/conf.d/default.conf"
      - "./main/www:/www"
    restart: "always"

  php-main:
    container_name: php-fpm-main
    build:
      context: main/php/
      dockerfile: Dockerfile
    depends_on:
      - nginx-main
    volumes:
      - "./main/www:/www"

  mysql_server:
    container_name: mysql_server
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
    ports:
      - "8001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: "always"